### ISSUE TITLE
incorrect results shown for isdiffpos=f sources

### ISSUE THREAD

**Issue by franzebauer** [alercebroker/ztf_explorer#148]
Some examples => https://alerce.online/object/ZTF18aauselm , https://alerce.online/object/ZTF18abvkswd, https://alerce.online/object/ZTF18aaxljll, ... 
=> xmatched as spectroscopically id'd SN II or IIn, but light curve continues to increase up to 500+ days!?! Appears that variable is stronger in the template image than science (so isdiffpos = f), but ALeRCE is reporting positive magnitudes.

**Comment by fforster** [comment]
The problem with these SNe is that template contains the supernova as you say. You can confirm this by downloading the light curve csv and looking at the isdiffpos column. Because the magnitude system only accepts positive values, the only thing we can do is to report somewhere that the difference is negative. One idea is to show it when you hover on top of each point, another is to convert everything to flux units. What do you suggest?

**Comment by franzebauer** [comment]
We need to be able to identify these cases and flag them so they do not turn up in the search results. The search engine currently thinks that these are detections, but by the looks of many science images they should not be. This needs to be fixed before we go public. If I choose sources with 100 detections, they need to be real detections. Not blank science images, as so many are.

Regarding what to actually show for the light curves, they must be plotted as upper limits in magnitude at the depth of the science image. Switching to flux might be ok, but would still be problematic if we maintain a log scale, which I think we essentially have to. Perhaps all of this will be fixed once ZTF provides forced photometry. But until then, we need a stopgap.

**Comment by fforster** [comment]
I agree that we must be able to identify these automatically, but I prefer to add a warning or group them in a special class rather to turn everything into upper limits. If you do this you lose a lot of information, e.g. in AGN and variable stars almost everything could become upper limits. Negative information is very relevant.

An alternative is to measure the flux in the science, but this is not easy, since there could be a galaxy at the position of the source. I would try not classify anything with a negative fluxes as any of the transient classes. At some point we were using the number of negative detections as a feature, this would help in this respect. Also note that we are manually removing all these cases from the training set.

**Comment by franzebauer** [comment]
Right. Hrm. Is there a way to distinguish between diff images where there is a detectable source in the science images and those where the science images are blank/unchanging? We would need to difference the science images amongst themselves, or at least have forced photometry (which we are still waiting for from ZTF).

**Comment by fforster** [comment]
I cannot think of an easy way, specially if there is a galaxy.

**Comment by franzebauer** [comment]
With forced photometry, we could compare the expected flux of the transient (based on the difference image when ifdiffpos = f ) to the error from the forced photometry. If the expected flux is >2-3 times the error, it remains detected, otherwise it is a limit. This should account for whatever flux in the aperture.

**Comment by fforster** [comment]
Yes, but we don't have the psf to do reliable forced photometry.
