### ISSUE TITLE
large light curve calibration offsets (0.5-3 mag) when using different nearby stars.

### ISSUE THREAD

**Issue by franzebauer** [alercebroker/ztf_explorer#151]
for some sources (https://alerce.online/object/ZTF18aauselm, https://alerce.online/object/ZTF17aaaowrw, etc.), there are 2-3 different calibrations which are offset by ~0.5-3 mag each (known issue with ZTF I believe, but would be good to mention it in the documentation, particularly if it is not going to be resolved before public release). Is there any way to identify/flag these?

**Comment by fforster** [comment]
This problem is not related to calibration. This happens because the object is contained in the reference image and there are more than one reference images and therefore reference fluxes. This is corrected when the the nearest PanSTARRS object is a star, by computing the total apparent magnitude and its error:
![errors](https://user-images.githubusercontent.com/5090828/69487490-edc22780-0dfe-11ea-92ae-fb297571a671.png)

However, when the nearest PanSTARRS source is a galaxy it assumes that the source is not in the reference. Unfortunately the data is not very useful when this happens, the only way to make the data useful is to know exactly then the reference frame was taken and work with flux differences when comparing to a model (see Förster et al. 2018, Nat Ast), but this is not provided in the ZTF stream. An alternative is to extract the reference flux at the source in each image, but this too complicated to be done automatically and it is affected by varying seeing conditions.

You can check the different reference fields by downloading the light curve csv file and looking at the field and rcid fields.

Perhaps we could add a warning when the flux difference is negative, the source is close to a galaxy, and there are more than one combination of field and rcid in the light curve.

**Comment by franzebauer** [comment]
I would say at a minimum, there should be a flag to warn that the light curves are unreliable as is (and some description of this in the documentation). The ability to only choose one reference among the several would be another option, allowing to least salvage a portion of them for science (I guess this can be down by downloading the light curve, as you say). The best would be to have ZTF provide a fix for it. *shrug*
